In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'data.csv')

In [3]:
df

Transaction ID            Timestamp  \
0       914154e8-230a-426d-ab66-736efb9e11de  2024-06-22 04:06:38   
1       e0e1e4a0-da2e-421b-9a98-222a47e9bc91  2024-06-19 06:04:49   
2       8e9c0ae9-7452-4ae3-aa3f-073bacd085b6  2024-06-04 04:56:09   
3       fbd51157-353c-4365-bdb1-1c28649db235  2024-06-09 09:56:07   
4       81fba9b7-445c-4a3a-99d4-89e600575b46  2024-06-25 08:38:19   
...                                      ...                  ...   
110995  0f0cda32-acb4-43c5-b372-32db7489382d  2024-08-09 10:35:00   
110996  8df42965-4b89-41ba-9407-f484eb59c84c  2024-08-09 10:36:00   
110997  c48cdc24-e8ff-493f-992d-c784099959de  2024-08-09 10:37:00   
110998  074299ff-2225-4001-864a-99def75ec151  2024-08-09 10:38:00   
110999  105ce434-6dd3-4578-a9f5-50cb03756b02  2024-08-09 10:39:00   

            Sender Name          Sender UPI ID   Receiver Name  \
0             Tiya Mall      4161803452@okaxis  Mohanlal Golla   
1       Mohanlal Bakshi      8908837379@okaxis  Mehul Sankaran   
2           Kismat Bora       4633654150@okybl       Diya Goel   
3         Ayesha Korpal  7018842771@okhdfcbank    Rhea Kothari   
4           Jivin Batta       1977143985@okybl     Baiju Issac   
...                 ...                    ...             ...   
110995      Riya Thaker      4214380585@okaxis     Lakshya Jha   
110996       Sai Bansal       4619206306@oksbi       Abram Sem   
110997      Aarav Reddy      4691544678@okaxis  Saksham Talwar   
110998      Rudra Patel      5192300899@okaxis     Rudra Mehta   
110999     Aditya Singh      2360717570@okaxis    Vihaan Singh   

           Receiver UPI ID  Amount (INR)   Status  
0         7776849307@okybl   3907.340000   FAILED  
1        7683454560@okaxis   8404.550000  SUCCESS  
2       2598130823@okicici    941.880000  SUCCESS  
3        2246623650@okaxis   8926.000000  SUCCESS  
4         5245672729@okybl   2800.550000  SUCCESS  
...                    ...           ...      ...  
110995   9234552942@okaxis    317.595193  SUCCESS  
110996   3879550385@okaxis   4989.205795  SUCCESS  
110997   6819956779@okaxis   1150.815901   FAILED  
110998   9245415422@okaxis   4401.719444  SUCCESS  
110999   6421519278@okaxis   8031.387804   FAILED  

[111000 rows x 8 columns]

In [4]:
df.columns

Index(['Transaction ID', 'Timestamp', 'Sender Name', 'Sender UPI ID',
       'Receiver Name', 'Receiver UPI ID', 'Amount (INR)', 'Status'],
      dtype='object')

In [5]:
df['Status'].value_counts()

Status
SUCCESS    85565
FAILED     25435
Name: count, dtype: int64

1. Now I will extract day,time,month and year from transaction timestamp.
2. I will extract upi id after @ for both reciever as well as sender.
3. I will drop Transaction Id, Reciever name and Sender Name from df.

In [6]:
df.drop(columns=['Transaction ID','Sender Name','Receiver Name'],inplace=True)

In [7]:
df

Timestamp          Sender UPI ID     Receiver UPI ID  \
0       2024-06-22 04:06:38      4161803452@okaxis    7776849307@okybl   
1       2024-06-19 06:04:49      8908837379@okaxis   7683454560@okaxis   
2       2024-06-04 04:56:09       4633654150@okybl  2598130823@okicici   
3       2024-06-09 09:56:07  7018842771@okhdfcbank   2246623650@okaxis   
4       2024-06-25 08:38:19       1977143985@okybl    5245672729@okybl   
...                     ...                    ...                 ...   
110995  2024-08-09 10:35:00      4214380585@okaxis   9234552942@okaxis   
110996  2024-08-09 10:36:00       4619206306@oksbi   3879550385@okaxis   
110997  2024-08-09 10:37:00      4691544678@okaxis   6819956779@okaxis   
110998  2024-08-09 10:38:00      5192300899@okaxis   9245415422@okaxis   
110999  2024-08-09 10:39:00      2360717570@okaxis   6421519278@okaxis   

        Amount (INR)   Status  
0        3907.340000   FAILED  
1        8404.550000  SUCCESS  
2         941.880000  SUCCESS  
3        8926.000000  SUCCESS  
4        2800.550000  SUCCESS  
...              ...      ...  
110995    317.595193  SUCCESS  
110996   4989.205795  SUCCESS  
110997   1150.815901   FAILED  
110998   4401.719444  SUCCESS  
110999   8031.387804   FAILED  

[111000 rows x 5 columns]

# Data Preprocessing

In [8]:
def get_year(row):
    return row[:4]
def get_month(row):
    return row[5:7]
def get_day(row):
    return row[8:10]

In [9]:
df['Year']=df['Timestamp'].apply(get_year)
df['Month']=df['Timestamp'].apply(get_month)
df['Day']=df['Timestamp'].apply(get_day)

In [10]:
df['Year']=df['Year'].astype('int')
df['Month']=df['Month'].astype('int')
df['Day']=df['Day'].astype('int')

In [11]:
print(df['Year'].value_counts())
print(df['Month'].value_counts())
print(df['Day'].value_counts())

Year
2024    111000
Name: count, dtype: int64
Month
7     45606
6     44936
8     13009
1       877
10      859
5       855
3       855
12      828
9       815
4       803
11      797
2       760
Name: count, dtype: int64
Day
3     4704
6     4703
1     4695
4     4693
7     4683
2     4679
8     4667
5     4657
9     3886
23    3281
21    3274
12    3270
18    3256
17    3255
27    3253
14    3248
25    3248
24    3247
28    3243
19    3233
20    3231
22    3226
15    3223
26    3223
11    3222
10    3216
29    3213
30    3213
16    3212
13    3205
31    1641
Name: count, dtype: int64


In [12]:
df['Timestamp']=df['Timestamp'].apply(lambda x: pd.to_datetime(x))

In [13]:
def get_hours(row):
    return row.hour
def get_minutes(row):
    return row.minute

In [14]:
df['Hour']=df['Timestamp'].apply(get_hours)
df['Minute']=df['Timestamp'].apply(get_minutes)

In [15]:
df.drop(columns=['Year','Month','Timestamp'],inplace=True)

In [16]:
df

Sender UPI ID     Receiver UPI ID  Amount (INR)   Status  Day  \
0           4161803452@okaxis    7776849307@okybl   3907.340000   FAILED   22   
1           8908837379@okaxis   7683454560@okaxis   8404.550000  SUCCESS   19   
2            4633654150@okybl  2598130823@okicici    941.880000  SUCCESS    4   
3       7018842771@okhdfcbank   2246623650@okaxis   8926.000000  SUCCESS    9   
4            1977143985@okybl    5245672729@okybl   2800.550000  SUCCESS   25   
...                       ...                 ...           ...      ...  ...   
110995      4214380585@okaxis   9234552942@okaxis    317.595193  SUCCESS    9   
110996       4619206306@oksbi   3879550385@okaxis   4989.205795  SUCCESS    9   
110997      4691544678@okaxis   6819956779@okaxis   1150.815901   FAILED    9   
110998      5192300899@okaxis   9245415422@okaxis   4401.719444  SUCCESS    9   
110999      2360717570@okaxis   6421519278@okaxis   8031.387804   FAILED    9   

        Hour  Minute  
0          4       6  
1          6       4  
2          4      56  
3          9      56  
4          8      38  
...      ...     ...  
110995    10      35  
110996    10      36  
110997    10      37  
110998    10      38  
110999    10      39  

[111000 rows x 7 columns]

In [17]:
def get_upi(row):
    indx=row.index('@')
    return row[indx+1:]

In [18]:
df['Sender']=df['Sender UPI ID'].apply(get_upi)
df['Receiver']=df['Receiver UPI ID'].apply(get_upi)

In [19]:
df.drop(columns=['Sender UPI ID','Receiver UPI ID'],inplace=True)

In [20]:
df

Amount (INR)   Status  Day  Hour  Minute      Sender Receiver
0        3907.340000   FAILED   22     4       6      okaxis    okybl
1        8404.550000  SUCCESS   19     6       4      okaxis   okaxis
2         941.880000  SUCCESS    4     4      56       okybl  okicici
3        8926.000000  SUCCESS    9     9      56  okhdfcbank   okaxis
4        2800.550000  SUCCESS   25     8      38       okybl    okybl
...              ...      ...  ...   ...     ...         ...      ...
110995    317.595193  SUCCESS    9    10      35      okaxis   okaxis
110996   4989.205795  SUCCESS    9    10      36       oksbi   okaxis
110997   1150.815901   FAILED    9    10      37      okaxis   okaxis
110998   4401.719444  SUCCESS    9    10      38      okaxis   okaxis
110999   8031.387804   FAILED    9    10      39      okaxis   okaxis

[111000 rows x 7 columns]

In [21]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split

In [22]:
le=LabelEncoder()
df['Status']=le.fit_transform(df['Status'])

In [23]:
df

Amount (INR)  Status  Day  Hour  Minute      Sender Receiver
0        3907.340000       0   22     4       6      okaxis    okybl
1        8404.550000       1   19     6       4      okaxis   okaxis
2         941.880000       1    4     4      56       okybl  okicici
3        8926.000000       1    9     9      56  okhdfcbank   okaxis
4        2800.550000       1   25     8      38       okybl    okybl
...              ...     ...  ...   ...     ...         ...      ...
110995    317.595193       1    9    10      35      okaxis   okaxis
110996   4989.205795       1    9    10      36       oksbi   okaxis
110997   1150.815901       0    9    10      37      okaxis   okaxis
110998   4401.719444       1    9    10      38      okaxis   okaxis
110999   8031.387804       0    9    10      39      okaxis   okaxis

[111000 rows x 7 columns]

In [24]:
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
categorical_columns

['Sender', 'Receiver']

In [25]:
encoder=OneHotEncoder(sparse_output=False,drop='first')
ohe_data=encoder.fit_transform(df[categorical_columns])

In [26]:
new_df=pd.DataFrame(ohe_data,columns=encoder.get_feature_names_out(categorical_columns))

In [27]:
# Concatenate the one-hot encoded dataframe with the original dataframe
df_encoded = pd.concat([df, new_df], axis=1)

# Drop the original categorical columns
df_encoded = df_encoded.drop(categorical_columns, axis=1)

In [28]:
df_encoded

Amount (INR)  Status  Day  Hour  Minute  Sender_okhdfcbank  \
0        3907.340000       0   22     4       6                0.0   
1        8404.550000       1   19     6       4                0.0   
2         941.880000       1    4     4      56                0.0   
3        8926.000000       1    9     9      56                1.0   
4        2800.550000       1   25     8      38                0.0   
...              ...     ...  ...   ...     ...                ...   
110995    317.595193       1    9    10      35                0.0   
110996   4989.205795       1    9    10      36                0.0   
110997   1150.815901       0    9    10      37                0.0   
110998   4401.719444       1    9    10      38                0.0   
110999   8031.387804       0    9    10      39                0.0   

        Sender_okicici  Sender_oksbi  Sender_okybl  Receiver_okhdfcbank  \
0                  0.0           0.0           0.0                  0.0   
1                  0.0           0.0           0.0                  0.0   
2                  0.0           0.0           1.0                  0.0   
3                  0.0           0.0           0.0                  0.0   
4                  0.0           0.0           1.0                  0.0   
...                ...           ...           ...                  ...   
110995             0.0           0.0           0.0                  0.0   
110996             0.0           1.0           0.0                  0.0   
110997             0.0           0.0           0.0                  0.0   
110998             0.0           0.0           0.0                  0.0   
110999             0.0           0.0           0.0                  0.0   

        Receiver_okicici  Receiver_oksbi  Receiver_okybl  
0                    0.0             0.0             1.0  
1                    0.0             0.0             0.0  
2                    1.0             0.0             0.0  
3                    0.0             0.0             0.0  
4                    0.0             0.0             1.0  
...                  ...             ...             ...  
110995               0.0             0.0             0.0  
110996               0.0             0.0             0.0  
110997               0.0             0.0             0.0  
110998               0.0             0.0             0.0  
110999               0.0             0.0             0.0  

[111000 rows x 13 columns]

In [29]:
df_encoded.corr()

Amount (INR)    Status       Day      Hour    Minute  \
Amount (INR)             1.000000  0.004089  0.004800  0.001265  0.000063   
Status                   0.004089  1.000000 -0.013194 -0.003744 -0.004063   
Day                      0.004800 -0.013194  1.000000  0.003652  0.001239   
Hour                     0.001265 -0.003744  0.003652  1.000000  0.001460   
Minute                   0.000063 -0.004063  0.001239  0.001460  1.000000   
Sender_okhdfcbank        0.004611  0.003457 -0.001646  0.000004 -0.004556   
Sender_okicici           0.002520  0.003311 -0.000911 -0.002763 -0.005835   
Sender_oksbi             0.003529  0.002365  0.002691 -0.002840 -0.004302   
Sender_okybl             0.002057  0.000237  0.002745  0.000675 -0.001412   
Receiver_okhdfcbank     -0.001357 -0.000164 -0.002706 -0.005028  0.002632   
Receiver_okicici         0.000396 -0.004782  0.000525  0.003539  0.001850   
Receiver_oksbi          -0.001110  0.003255 -0.000222  0.001009 -0.002405   
Receiver_okybl           0.005406 -0.000516  0.003166  0.001522  0.002408   

                     Sender_okhdfcbank  Sender_okicici  Sender_oksbi  \
Amount (INR)                  0.004611        0.002520      0.003529   
Status                        0.003457        0.003311      0.002365   
Day                          -0.001646       -0.000911      0.002691   
Hour                          0.000004       -0.002763     -0.002840   
Minute                       -0.004556       -0.005835     -0.004302   
Sender_okhdfcbank             1.000000       -0.018272     -0.018858   
Sender_okicici               -0.018272        1.000000     -0.019120   
Sender_oksbi                 -0.018858       -0.019120      1.000000   
Sender_okybl                 -0.017759       -0.018005     -0.018583   
Receiver_okhdfcbank           0.010307        0.017559      0.016338   
Receiver_okicici              0.017020        0.019870      0.014680   
Receiver_oksbi                0.017862        0.018163      0.023451   
Receiver_okybl                0.017275        0.017052      0.014414   

                     Sender_okybl  Receiver_okhdfcbank  Receiver_okicici  \
Amount (INR)             0.002057            -0.001357          0.000396   
Status                   0.000237            -0.000164         -0.004782   
Day                      0.002745            -0.002706          0.000525   
Hour                     0.000675            -0.005028          0.003539   
Minute                  -0.001412             0.002632          0.001850   
Sender_okhdfcbank       -0.017759             0.010307          0.017020   
Sender_okicici          -0.018005             0.017559          0.019870   
Sender_oksbi            -0.018583             0.016338          0.014680   
Sender_okybl             1.000000             0.023675          0.016739   
Receiver_okhdfcbank      0.023675             1.000000         -0.018764   
Receiver_okicici         0.016739            -0.018764          1.000000   
Receiver_oksbi           0.015476            -0.018648         -0.018040   
Receiver_okybl           0.021667            -0.019042         -0.018421   

                     Receiver_oksbi  Receiver_okybl  
Amount (INR)              -0.001110        0.005406  
Status                     0.003255       -0.000516  
Day                       -0.000222        0.003166  
Hour                       0.001009        0.001522  
Minute                    -0.002405        0.002408  
Sender_okhdfcbank          0.017862        0.017275  
Sender_okicici             0.018163        0.017052  
Sender_oksbi               0.023451        0.014414  
Sender_okybl               0.015476        0.021667  
Receiver_okhdfcbank       -0.018648       -0.019042  
Receiver_okicici          -0.018040       -0.018421  
Receiver_oksbi             1.000000       -0.018307  
Receiver_okybl            -0.018307        1.000000

# Splitting X and Y

In [30]:
X=df_encoded.drop(columns=['Status'])
y=df_encoded['Status']

In [31]:
from imblearn.over_sampling import SMOTE
sm=SMOTE()
x_res,y_res=sm.fit_resample(X,y)

In [32]:
x_res

Amount (INR)  Day  Hour  Minute  Sender_okhdfcbank  Sender_okicici  \
0        3907.340000   22     4       6                0.0             0.0   
1        8404.550000   19     6       4                0.0             0.0   
2         941.880000    4     4      56                0.0             0.0   
3        8926.000000    9     9      56                1.0             0.0   
4        2800.550000   25     8      38                0.0             0.0   
...              ...  ...   ...     ...                ...             ...   
171125   8903.370678   16     3      36                0.0             0.0   
171126    732.208767    7    17      18                0.0             0.0   
171127   6288.559282   25    11      11                0.0             0.0   
171128   3860.850530   11    11      55                0.0             0.0   
171129   4576.417951    5     5       6                0.0             0.0   

        Sender_oksbi  Sender_okybl  Receiver_okhdfcbank  Receiver_okicici  \
0                0.0           0.0                  0.0          0.000000   
1                0.0           0.0                  0.0          0.000000   
2                0.0           1.0                  0.0          1.000000   
3                0.0           0.0                  0.0          0.000000   
4                0.0           1.0                  0.0          0.000000   
...              ...           ...                  ...               ...   
171125           0.0           0.0                  0.0          0.014598   
171126           0.0           0.0                  0.0          0.406698   
171127           0.0           0.0                  0.0          0.000000   
171128           0.0           0.0                  0.0          0.000000   
171129           0.0           0.0                  0.0          0.000000   

        Receiver_oksbi  Receiver_okybl  
0                  0.0             1.0  
1                  0.0             0.0  
2                  0.0             0.0  
3                  0.0             0.0  
4                  0.0             1.0  
...                ...             ...  
171125             0.0             0.0  
171126             0.0             0.0  
171127             0.0             0.0  
171128             0.0             0.0  
171129             0.0             0.0  

[171130 rows x 12 columns]

In [33]:
X_train,X_test,y_train,y_test=train_test_split(x_res,y_res,test_size=0.2,random_state=2024)

In [34]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((136904, 12), (34226, 12), (136904,), (34226,))

In [35]:
y_test

19832     1
169106    0
84135     1
101292    1
31522     1
         ..
32736     1
28295     1
102308    0
153555    0
169050    0
Name: Status, Length: 34226, dtype: int32

In [37]:
X_test.to_csv('xdata.csv')
y_test.to_csv('ydata.csv')
y_train.to_csv('y_train.csv')
X_train.to_csv('X_train.csv')

In [39]:
X_train.columns

Index(['Amount (INR)', 'Day', 'Hour', 'Minute', 'Sender_okhdfcbank',
       'Sender_okicici', 'Sender_oksbi', 'Sender_okybl', 'Receiver_okhdfcbank',
       'Receiver_okicici', 'Receiver_oksbi', 'Receiver_okybl'],
      dtype='object')

In [47]:
X_train['Day'].value_counts()

Day
7     6005
6     5974
4     5858
5     5812
3     5744
8     5691
2     5639
1     5191
9     4879
24    4271
25    4257
21    4229
23    4213
26    4213
10    4178
11    4173
22    4163
20    4156
27    4137
18    4126
12    4077
14    4059
19    4034
16    4025
17    4016
13    3969
15    3968
28    3877
29    3559
30    3069
31    1342
Name: count, dtype: int64

In [114]:
# scaler=MinMaxScaler()
# X_train=scaler.fit_transform(X_train)
# X_test=scaler.transform(X_test)

In [115]:
X_test

Amount (INR)  Day  Hour  Minute  Sender_okhdfcbank  Sender_okicici  \
19832    9710.496694    7     3      12                0.0             0.0   
169106   7621.160046    1    17       6                0.0             0.0   
84135    1331.214205   21    18      55                1.0             0.0   
101292   6943.952562    2    16      52                0.0             0.0   
31522    4492.672246   15     6       2                0.0             0.0   
...              ...  ...   ...     ...                ...             ...   
32736    8090.432640   16     2      16                0.0             1.0   
28295    4659.362094   13     0      15                0.0             0.0   
102308   2874.371739    3     9      48                0.0             0.0   
153555   9528.288948   20     8       6                0.0             0.0   
169050   1585.755795   18     8      30                0.0             0.0   

        Sender_oksbi  Sender_okybl  Receiver_okhdfcbank  Receiver_okicici  \
19832            0.0      0.000000                  0.0               0.0   
169106           0.0      0.000000                  0.0               0.0   
84135            0.0      0.000000                  0.0               0.0   
101292           0.0      0.000000                  0.0               0.0   
31522            0.0      0.000000                  0.0               0.0   
...              ...           ...                  ...               ...   
32736            0.0      0.000000                  0.0               0.0   
28295            0.0      0.000000                  0.0               0.0   
102308           0.0      0.000000                  0.0               0.0   
153555           0.0      0.641166                  0.0               0.0   
169050           0.0      0.000000                  0.0               0.0   

        Receiver_oksbi  Receiver_okybl  
19832              0.0             0.0  
169106             0.0             0.0  
84135              0.0             0.0  
101292             0.0             0.0  
31522              0.0             0.0  
...                ...             ...  
32736              0.0             0.0  
28295              0.0             0.0  
102308             0.0             0.0  
153555             0.0             0.0  
169050             0.0             0.0  

[34226 rows x 12 columns]

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

# Model Building and Evaluation

In [117]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [118]:
print(accuracy_score(lr.predict(X_train),y_train))

0.5067711681178052


In [119]:
print(accuracy_score(lr.predict(X_test),y_test))
print(confusion_matrix(lr.predict(X_test),y_test))

0.5068369076140945
[[8442 8104]
 [8775 8905]]


In [120]:
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier

In [121]:
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
et=ExtraTreesClassifier()

In [122]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [123]:
print(accuracy_score(dt.predict(X_test),y_test))

0.6719160871851808


In [45]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import numpy as np


# Define the parameter grid (search space)
param_dist = {
    'n_estimators': np.arange(100, 1000, 100),  # Number of trees from 100 to 1000
    'max_depth': [None] + list(np.arange(10, 110, 10)),  # Depth from 10 to 100 or None (no limit)
    'min_samples_split': np.arange(2, 20, 2),  # Minimum samples required to split a node
    'min_samples_leaf': np.arange(1, 20, 2),  # Minimum samples required at each leaf
    'max_features': ['auto', 'sqrt', 'log2'],  # Number of features considered at each split
    'bootstrap': [True, False]  # Whether to use bootstrapped samples
}

# Initialize the RandomForestClassifier
rf = RandomForestClassifier()

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=rf, 
                                   param_distributions=param_dist, 
                                   n_iter=100,  # Number of parameter settings sampled
                                   cv=3,        # 3-fold cross-validation
                                   verbose=2,   # Output verbosity
                                   random_state=42,  # Seed for reproducibility
                                   n_jobs=-1)   # Use all available cores

# Fit RandomizedSearchCV to the training data
random_search.fit(X_train, y_train)

# Print the best hyperparameters found
print("Best Hyperparameters:", random_search.best_params_)

# Use the best estimator to make predictions on the test set
best_rf = random_search.best_estimator_
y_pred = best_rf.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Print a detailed classification report (Precision, Recall, F1-Score for each class)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
75 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
75 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_param

Best Hyperparameters: {'n_estimators': 200, 'min_samples_split': 6, 'min_samples_leaf': 11, 'max_features': 'sqrt', 'max_depth': 70, 'bootstrap': False}
Accuracy: 0.7732

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.00      0.00      5038
           1       0.77      1.00      0.87     17162

    accuracy                           0.77     22200
   macro avg       0.76      0.50      0.44     22200
weighted avg       0.77      0.77      0.67     22200


Confusion Matrix:
[[    6  5032]
 [    2 17160]]


In [124]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [125]:
print(accuracy_score(rf.predict(X_test),y_test))

0.653655115993689


In [126]:
et.fit(X_train,y_train)

ExtraTreesClassifier()

In [127]:
print(accuracy_score(et.predict(X_test),y_test))

0.655086776135102


In [128]:
from sklearn.neighbors import KNeighborsClassifier

In [129]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [130]:
print(accuracy_score(knn.predict(X_test),y_test))
print(confusion_matrix(knn.predict(X_test),y_test))

0.7100449950330159
[[14610  7317]
 [ 2607  9692]]


In [131]:
new=[9769.81,25,2,16,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0]
prrd= knn.predict([new])

C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [132]:
prrd

array([1])

In [133]:
sucess=[9341.93,7,13,27,0,0,1,0,0,1,0,0]

pred= et.predict([new])
print(pred)


[1]


C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(


In [134]:
import joblib
joblib.dump(rf,'rfk.joblib')
joblib.dump(dt,'dec.joblib')
joblib.dump(lr,'lrt.joblib')

['lrt.joblib']

In [140]:

new=[2434.9,	1,	8,	15,	0,	0,	0,	0,	0,	0,	0,	0]
pred = rf.predict([new])
pred

C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [141]:
zero=[6644.74	,28	,5,	21	,0	,0	,1,	0,	0	,0,	0,	1]
pred1 = rf.predict([zero])
pred1

C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [142]:
zero=[753.02,	4,	15	,16,	1	,0,	0,	0	,0,	0,0,0]
pred1 = rf.predict([zero])
pred1

C:\Users\085\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])